Vagrant.configure("2") do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "dev-vagrant"
  config.vm.hostname = "prod-pipeline-frontend-01"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://ubuntuone.com/7NVFjt8XFVjNr2Sj6yjtMF"
  #config.vm.box_url = "file:///Users/carlosg/workspace/vagrant/boxes/develenv-centos_6.4-x86_64-minimal.box"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  #config.vm.network :forwarded_port, guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # La ip debe pertencer al rango del interfaz vboxnet0
  config.vm.network :private_network, ip: "192.168.33.5"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "/Users/carlosg/workspace", "/home/vagrant/workspace"
  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
     vb.gui = false
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
     vb.customize ["modifyvm", :id, "--memory", "512"]
  end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file ci.pp in the manifests_path directory.
  config.vm.provision :puppet, :module_path => "modules"  do |puppet|
     puppet.manifests_path = "manifests"
     puppet.manifest_file  = "pipeline.pp"
     puppet.module_path = "modules"
     #puppet.options = "--verbose --debug --modulepath ../modules-0"
     puppet.options = "--verbose --debug"
  end

  
  #######################
  # auto-update plugin
  #######################

  # install it with:
  # $ vagrant plugin install vagrant-vbguest

  # set auto_update to false, if do NOT want to check the correct additions 
  # version when booting this machine
  # config.vbguest.auto_update = true

  # do NOT download the iso file from a webserver
  config.vbguest.no_remote = false

end
